### ISSUE TITLE
Export for private repoistory

### ISSUE THREAD

**Issue by MoatazAbdallh** [Expium/ghi2jira#7]
Hello
I need to export issues from private repo every time I got the following issue, 
Error from GitHub. API returned 404, repo owner, name, or auth is wrong
Regards

**Comment by konrad-garus** [comment]
I have just tested it against this project, and it ran as expected.

The error sounds like your github project or user name are incorrect. For example, to export this project, I had to use:

```
{
  :ghuser "Expium"
  :ghproject "ghi2jira"
}
```

If you look at the project URL in GitHub (e.g. https://github.com/Expium/ghi2jira), ghuser is the first segment and ghproject the second one.

**Comment by kylecordes** [comment]
Two more ideas:

* Someone reported trouble a while back, and it turned out they have swapped the username in `:auth` with the username in `:ghuser`.
*Github has been having technical uptime trouble today. https://status.github.com/

**Comment by MoatazAbdallh** [comment]
Ok, Also is there any option to fetch the last 100 issues from github instead of fetching all issues.

**Comment by kylecordes** [comment]
@MoatazAbdallh There isn't a configuration option to do it, and I've long forgotten the details of how it works... but looking at the source code comments it appears you can tweak a line of code to limit how much data it retrieves.

https://github.com/Expium/ghi2jira/blob/master/src/ghijira/core.clj#L43

**Comment by kylecordes** [comment]
The software definitely works for private repositories - I've used it that way several times myself, and various users have written and describe their good results. Therefore I will close this issue.
